#!/bin/bash

select=$(echo -e " Shutdown\n Restart\n Log Out\n Hibernate\n Sleep" | rofi -dmenu -theme westsidebar.rasi)

case "$select" in
    " Shutdown")
        systemctl poweroff
        ;;
    " Restart")
        systemctl reboot
        ;;
    " Log Out")
        swaymsg exit
        ;;
    " Hibernate")
        systemctl hibernate
        ;;
    " Sleep")
        systemctl suspend
        ;;
    *)
        ;;
esac

